### ISSUE TITLE
Minor fixes with server

### ISSUE THREAD

**Issue by DhairyaMajmudar** [PatilHarshh/Kaam-Do#1]
- [ ] Move nodemon to dev dependencies object

- [ ] Also add separate scripts `"run":"node server.js"` and `"dev":"nodemon server.js"` in scripts obj.

- [ ] Remove unwanted "test" script if there is no planning to add e2e and frontend testing in future.

- [ ] Update readme.md with instruction to run server folder along with client folder

**Comment by Melvin0070** [comment]
Please assign this to me

**Comment by CS251000** [comment]
Request for assignment of this issue

**Comment by shambhaveesrivastava12** [comment]
could u please assign this to me

**Comment by ShoveetSingh** [comment]
Hey mate, love to see that there are some server side issues which i would like to debug and fix it.
Assign the project to me . I am Shoveet and being selected for gssoc 2024 as a contributor.
I have a strong fundamentals in backend technologies.
Thank you.

**Comment by rawani123** [comment]
Can you assign this issue to me

**Comment by Himanshityagii24** [comment]
You can assign me this task, I have good foundation of backend.
