### ISSUE TITLE
Feat: Add a Pull Request Template

### ISSUE THREAD

**Issue by Asymtode712** [PatilHarshh/Kaam-Do#101]
### Describe the feature

The solution is to implement a standardized pull request template. This template should include sections that prompt the author to provide essential information, such as:

- A brief description of the changes.
- The issue or feature being addressed (linked to relevant issue tracker entries).
- Screenshots or GIFs (if the changes include UI modifications).
- Checklist for confirming code adheres to coding standards, tests are added/updated, and documentation is updated.

### Add ScreenShots

![Pull Req](https://github.com/PatilHarshh/Kaam-Do/assets/115717746/b9f44b97-d0d3-4f52-b39f-dc0902cccadc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@PatilHarshh please assign me this issue under gssoc'24

**Comment by suhanipaliwal** [comment]
Duplicate issue. Already raised #82
