### ISSUE TITLE
Feat: Add a floating button to scroll to top

### ISSUE THREAD

**Issue by Asymtode712** [PatilHarshh/Kaam-Do#103]
### Describe the feature

Adding a floating button which when clicked would scroll back to the top.

### Add ScreenShots

![float btn](https://github.com/PatilHarshh/Kaam-Do/assets/115717746/a6e0a594-24de-4cb1-bbb3-bee68f67720c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@PatilHarshh can you please mention the issue which was similar to this which lead you to label it as "duplicate"

**Comment by Asymtode712** [comment]
@PatilHarshh I had already checked all th existing issues and I didn't found any issue related to scrolling back to top that's why I raised this one. Check the issues once

**Comment by PatilHarshh** [comment]
#42 is the Issue !
