### ISSUE TITLE
Feat:  making changes in logo

### ISSUE THREAD

**Issue by reshamsai150** [PatilHarshh/Kaam-Do#109]
### Describe the feature

Your logo is often the first thing visitors notice when they land on your website.
A well-designed logo can instantly captivate attention and create a positive initial interaction
I am looking forward to contributing to this issue @PatilHarshh 

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/164533685/08ca30f9-d797-439c-ba4e-a70b4252df4c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go Ahead !! @reshamsai150

**Comment by ZarnaPathak** [comment]
I would like to contribute to this Issue **@PatilHarshh** . Please assign this issue to me, so I can begin working on it
