### ISSUE TITLE
Add Code_Of_Conduct.md file.

### ISSUE THREAD

**Issue by Pranjalll01** [PatilHarshh/Kaam-Do#11]
Pranjal Kushwaha here , Contributor@GSSoc'24
repo currently lacks a codeofconduct.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A Code_Of_Conduct.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

could ypu please assign this to me ?

**Comment by aditi-sharma-2004** [comment]
Hi, Aditi Sharma this side , I would love to work on this issue.
Please assign it to me. GSSoC'24

**Comment by PatilHarshh** [comment]
@Pranjalll01 Go Ahead !

**Comment by officeneerajsaini** [comment]
@PatilHarshh assign to me this issue , PranjalII01 already taken so long.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by PatilHarshh** [comment]
Go Ahead ! @Pranjalll01

**Comment by PatilHarshh** [comment]
@aditi-sharma-2004 Go Ahead !! Complete this issue ASAP !

**Comment by officeneerajsaini** [comment]
@PatilHarshh this issue no longer exists, you can close this issue
