### ISSUE TITLE
BUG: Signup button not working

### ISSUE THREAD

**Issue by soham0005** [PatilHarshh/Kaam-Do#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On Click of Signup button, loader pops and nothing is displayed

Solutions to be provided:-
1) Signup Page to display 
2) Functionality of Signup

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by soham0005** [comment]
Hello @PatilHarshh, Can i work on this bug?

**Comment by tishubohra** [comment]
Hey @PatilHarshh , Please Let me work on this.
