### ISSUE TITLE
Adding social media icons.

### ISSUE THREAD

**Issue by Soumya6Tiwari** [PatilHarshh/Kaam-Do#116]
### Describe the feature

Adding other social media icons such as github , discord in the footer section of the website

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/117037441/79eec5a7-eb72-4cbc-ba1d-e299c8dc0e76)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EmazinUs** [comment]
@PatilHarshh  assign me this issue under gssoc 2024.

**Comment by yuvikaKathaith** [comment]
Is someone still working on this? if not, I'm a contributor at GSSOC24 and I would like to work on this issue. Please assign this to me.
