### ISSUE TITLE
[FEATURE] Implement the 'Notification' Section in Navbar

### ISSUE THREAD

**Issue by yashmandi** [PatilHarshh/Kaam-Do#119]
### Describe the feature

Adding the Notification Section in the Navbar will notify the job-seeker to get the notifications, messages and updates about the companies he's applied for or we can also show the suggestions of jobs in this section.

Would like to work on this feature. Request you to assign this task under GSSoC '24

### Add ScreenShots

We can implement the Notification Section right next to 'Upload Job'

![navbar](https://github.com/PatilHarshh/Kaam-Do/assets/132436131/1499da53-c2cf-4932-a7e9-b4fc6e0f835d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
Sir, I would really like to work on this issue under Gssoc'24, so please assign it to me.

**Comment by ujj654** [comment]
I  want to work on this issue. Please assign this issue to me.
