### ISSUE TITLE
Create profile for user and job providers.

### ISSUE THREAD

**Issue by drockparashar** [PatilHarshh/Kaam-Do#12]
Can create profile page for users and job posters.
User can view the status of the jobs they have applied for and the job posters can see the analytics for their job posting like number of applicants. 

I would like to contribute under GSSOC'24

**Comment by rushiii3** [comment]
Hey @PatilHarshh, I'm a GSSOC'24 contributor. I'd like to create the profile page for user and job providers

**Comment by PatilHarshh** [comment]
@drockparashar This can be implemented in Admin Dashboard ! would you want to proceed with it ?

**Comment by drockparashar** [comment]
> @drockparashar This can be implemented in Admin Dashboard ! would you want to proceed with it ?

Sure, I will do it right-away but it will also require admin side login, shall I raise another issue for creating admin login?

**Comment by pulkit49** [comment]
I can help you with that. Please assign me under GSSOC 2024.
