### ISSUE TITLE
Feat: Add Favicon

### ISSUE THREAD

**Issue by Muhammad-Owais-Warsi** [PatilHarshh/Kaam-Do#122]
### Describe the feature

Add the Favicon related to the website instead of using vite icon

### Add ScreenShots

![Screenshot 2024-05-22 143010](https://github.com/PatilHarshh/Kaam-Do/assets/133518394/c91d88cb-3171-4a3d-a558-46931d778b7f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EmazinUs** [comment]
@PatilHarshh  assign me this issue under gssoc 2024.
