### ISSUE TITLE
Adding blogs in Blogs section

### ISSUE THREAD

**Issue by Chandana-756** [PatilHarshh/Kaam-Do#128]
As I have noticed that when I clicked on the blogs section in the webpage, no blogs are being displayed. So I would like to add some blogs related to job search tips, resume writing guidance, and interview techniques, which can enhance a job seeker’s chances of success.

Screeshot:
![image](https://github.com/PatilHarshh/Kaam-Do/assets/94692989/b090a9c6-0306-4b7e-99a6-d5a9e5a8c791)

I would like to work on this issue under GSSOC'24.

**Comment by pspriyanshu601** [comment]
@PatilHarshh Please assign this issue to me, I want to work on this issue
