### ISSUE TITLE
Add new page for popular search jobs

### ISSUE THREAD

**Issue by ankitgupta143** [PatilHarshh/Kaam-Do#133]
### Describe the feature

I can add new page for the jobs for fresher, jobs for women, work from home jobs, part time jobs in frontend with best hover effect.
Also I can improve the cards with best design.
@PatilHarshh Kindly assign me the Issue.

### Add ScreenShots

![Uploading Screenshot 2024-05-24 142920.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ankitgupta143** [comment]
@PatilHarshh 
![Screenshot 2024-05-24 142920](https://github.com/PatilHarshh/Kaam-Do/assets/114281117/88902c32-bc94-40fe-91a9-7fe49748f41a)

**Comment by PatilHarshh** [comment]
Go Ahead @ankitgupta143
