### ISSUE TITLE
Dockerize the app

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [PatilHarshh/Kaam-Do#135]
### Describe the feature

I want to dockerize the mern app so that in future when someone fork the repo in different nodejs environment then he can easily use the app

### Add ScreenShots

no screenshot required

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by iritikyadav123** [comment]
assign  me
