### ISSUE TITLE
Feat:Fixing the cards styling on the home page

### ISSUE THREAD

**Issue by siddheshhr** [PatilHarshh/Kaam-Do#136]
### Describe the feature

1. Increased Font Size: Category titles and position counts have larger and bolder fonts.
2. Hover Effects: Cards slightly enlarge and change color when hovered over.
3. Consistent Design: All cards have a unified design with rounded corners and subtle shadows.
4. Aligned Text: Text within each card is centered and well-aligned.
5. Improved Spacing: Adequate padding and margin ensure the cards have enough white space.
6. Responsive Layout: Cards are displayed in a neat, responsive grid layout that adjusts based on screen size.

### Add ScreenShots

<img width="220" alt="image" src="https://github.com/PatilHarshh/Kaam-Do/assets/139670479/aafaebfd-75f0-493e-b52f-72b582dd5d07">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by siddheshhr** [comment]
please assign this issue to me

**Comment by EmazinUs** [comment]
@PatilHarshh  assign me this issue under gssoc 2024.
