### ISSUE TITLE
HIDDEN BUG🐞 : Routing Navigation Errors For The Pages 

### ISSUE THREAD

**Issue by MastanSayyad** [PatilHarshh/Kaam-Do#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @PatilHarshh 
I was just checking the website and I found that The navigations to the pages only work for a short time, when you refresh the page, it shows a 404 page. except the home page. (You can check that)

![image](https://github.com/PatilHarshh/Kaam-Do/assets/101971980/87796323-9d04-4325-acf9-cce10af6405f)

As you can see **It shows a 404 page.**

- Based on my knowledge it only happens if you don't configure your `vercel.json` 
- The **routes don't get recognized except the "/" Home page routes**. 

I have checked for the other Page routes such as _"Demos/Find Jobs/About/Companies/Candidates/Blogs/Sign In/Subpages"_

![image](https://github.com/PatilHarshh/Kaam-Do/assets/101971980/587733e3-77f4-4ae5-b6f0-e69e37ac3a81)

![image](https://github.com/PatilHarshh/Kaam-Do/assets/101971980/ca90757f-f2c1-41d1-aa47-30f2503ad415)

- Refresh these sections or pages it gives:

![image](https://github.com/PatilHarshh/Kaam-Do/assets/101971980/8d9fe42d-5599-43a7-bb95-cb674df77df8)

All these pages only work for short time and after refreshing they give 404 error, We can call it a Hidden BUG which can lead to a failed user experience and a bad impression.

I would like to take care of all these pages Navigation errors. as I have previously work on similar issue.
Could you please assign this issue to me under GSSOC 24??

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MastanSayyad** [comment]
Hey @PatilHarshh Could you please take a look at this issue and assign it to me??

**Comment by PatilHarshh** [comment]
Go Ahead !! @MastanSayyad
