### ISSUE TITLE
BUG: Sign In and Sign Up broken

### ISSUE THREAD

**Issue by woodwolfswee** [PatilHarshh/Kaam-Do#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Sign in simply does not work. It is not there. I would like to work on it if assigned to me. Thank you.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sudharsan0055** [comment]
I found no routes  are there, I can write the routes for sign in and signup so assign the issue to me. I just know to do that. Thank you
