### ISSUE TITLE
Forget password and reset password functionality

### ISSUE THREAD

**Issue by tusharyadav11** [PatilHarshh/Kaam-Do#15]
I want to work on the functionality of forget password and reset password functionality under Gssoc'24 . Please assign it to me @PatilHarshh

**Comment by PatilHarshh** [comment]
@tusharyadav11 First we have to develop register and login page !! then this can be implemented till then you can Wait

**Comment by VinayJangotra** [comment]
@PatilHarshh, I can develop register and login page also with the functionality of forget and reset password, Assign me the issue , I can write the both the frontend and backend for the pages and functionality, 
Thanking you

**Comment by Mandar007007** [comment]
Can you please assign me this task? As I have experience in making this feature
