### ISSUE TITLE
Feat: Adding Image to "Category" Section

### ISSUE THREAD

**Issue by its-kumar-yash** [PatilHarshh/Kaam-Do#153]
### Describe the feature

I'll add images to the category section. Kindly assign this to me.

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/97521394/608be12a-851f-49a2-830f-729bf07f4ed1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pulkit49** [comment]
I can help you with that. Please assign me under GSSOC 2024.
