### ISSUE TITLE
BUG:user click on card then display perticular company related information

### ISSUE THREAD

**Issue by Varsani2520** [PatilHarshh/Kaam-Do#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

user click on for example google company card then display google job related all the information 
![image](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/d5eac5e3-3e32-4c40-bdb4-d0a8d87ede9f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@PatilHarshh ,
assign this issue ,
i can do with design as well as functionality

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,this issue is related to functionality and also conditional based also backend also part ,so it is neccessary to add level 3 instead of level1

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,give me a response related to label

**Comment by Varsani2520** [comment]
if you give me label 3 i can create a most attractive web for you

**Comment by PatilHarshh** [comment]
Don't focus on Label Instead focus on the quality learning and contribution @Varsani2520

**Comment by Varsani2520** [comment]
Thank you @PatilHarshh for label focusing and understood me

**Comment by priyankMS** [comment]
Hi, I would like to work on this issue, please can you assign this to me.
