### ISSUE TITLE
BUG:sign up and login page design with functionality

### ISSUE THREAD

**Issue by Varsani2520** [PatilHarshh/Kaam-Do#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

user click on login button then open login page where verify the user is authenticate or not so on...
like this :
![image](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/f270a352-3c9e-4107-a24f-769b8b6803c4)
![image](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/47ef90b4-fdfd-422f-a8f0-22f5921f966c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Its already there @Varsani2520

**Comment by pulkit49** [comment]
I can help you with that. Please assign me under GSSOC 2024.
