### ISSUE TITLE
Feat: search by category page UI can be improved

### ISSUE THREAD

**Issue by AakankshaSarode** [PatilHarshh/Kaam-Do#159]
### Describe the feature

font size and design of card can be improved adding hovering effect and color in card  can be change it look more attractive.

### Add ScreenShots

![Screenshot 2024-05-29 124658](https://github.com/PatilHarshh/Kaam-Do/assets/142107143/7eb332f1-4600-45c6-b7a6-d532a60bfb64)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AakankshaSarode** [comment]
@PatilHarshh  please assign me this issue under GSSOC. I want to work on this issue.

**Comment by PatilHarshh** [comment]
Go Ahead @AakankshaSarode
