### ISSUE TITLE
Dark mode functionality

### ISSUE THREAD

**Issue by tusharyadav11** [PatilHarshh/Kaam-Do#16]
I want to contribute for adding the dark mode functionality under Gssoc'24. Please assign it to me @PatilHarshh

**Comment by PatilHarshh** [comment]
Seems Good ! Go Ahead @tusharyadav11

**Comment by tusharyadav11** [comment]
is there any deadline for doing this?

**Comment by PatilHarshh** [comment]
No There is no deadline . If any other is intersted for this issue and comments for assign  then i will give Deadline for it !

**Comment by RakshitaJain2126** [comment]
Hey, I want to contribute it too.It will be my first PR.Please assign it to me.

**Comment by tusharyadav11** [comment]
> Hey, I want to contribute it too.It will be my first PR.Please assign it to me.

@RakshitaJain2126  hey rakshita , write now i am working on this functionality . It would be grateful if you could another one .

**Comment by Manaswini123456** [comment]
Please assign this to me, so that I can start working on the same.

**Comment by tusharyadav11** [comment]
@PatilHarshh  completed the dark mode please check up my pull request 

Uploading dark mode functionality.mp4…
