### ISSUE TITLE
BUG: update twitter logo 

### ISSUE THREAD

**Issue by Amruta7203** [PatilHarshh/Kaam-Do#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current twitter logo is outdated. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Me-Nitin** [comment]
Assign it to me i can fix it and ya please add gssoc and level labels to issues

**Comment by PatilHarshh** [comment]
go ahead ! @Amruta7203
