### ISSUE TITLE
[FEAT] The HomePage UI can be improved. 

### ISSUE THREAD

**Issue by yashmandi** [PatilHarshh/Kaam-Do#167]
### Describe the feature

The Home Page is not much appealing, we should add some effects/animations on hover, which would make the users interactive and interesting.

### Add ScreenShots

Would like to add the effects to this below page:

![Screenshot (284)](https://github.com/PatilHarshh/Kaam-Do/assets/132436131/750643b7-84e8-49b8-9404-ee8149551429)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
what changes you want to make @yashmandi

**Comment by yashmandi** [comment]
> what changes you want to make @yashmandi

i would like to add the hover effect on the cards under 'Featured Job Offers', 'Find Best Companies' and 'Featured Cities' section in 'Home Page', and also in the cards present in 'Companies' Page. i will add shadow, and some attractive effect on hover

**Comment by priyankMS** [comment]
Hi, I would like to work on this issue, please can you assign this to me.
