### ISSUE TITLE
Feat: Route the  services section  of footer

### ISSUE THREAD

**Issue by aasthakourav20** [PatilHarshh/Kaam-Do#169]
### Describe the feature

 Can add the services section  and route it  as the current link is inactive .

### Add ScreenShots

![Screenshot (244)](https://github.com/PatilHarshh/Kaam-Do/assets/148269962/2069c507-72a2-455c-9f9c-5c0269f11f72)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pulkit49** [comment]
I can help you with that. Please assign me under GSSOC 2024.
