### ISSUE TITLE
create login and signup page

### ISSUE THREAD

**Issue by pinki2909** [PatilHarshh/Kaam-Do#17]
Hello sir,
I want to work on the functionality of login and register page under gssoc'24  @PatilHarshh

**Comment by vinay02103** [comment]
hello Mentor,I'd want to contribute to this project as a GSsoc'24 contributor. Please give me this issue to work on.

**Comment by VinayJangotra** [comment]
hello sir,
I want to work on this issue   the functionality of login and register page under gssoc'24 @PatilHarshh, I can fix within a day
Thanking you

**Comment by nikki-infinte** [comment]
Hello Nikita this side , 
I would wish to work on login and register  functionality  {contribution under GSSOC'24 contributor}.

**Comment by Ansh101112** [comment]
hello @PatilHarshh please assign this issue to me.

**Comment by InshiyaRavat** [comment]
I can help you with solving this issue. @PatilHarshh assign this issue to me under gssoc'24

**Comment by Mukesh-ghildiyal** [comment]
@PatilHarshh assign me this issue under gssoc'24, i am already working on it.

**Comment by yuvikaKathaith** [comment]
Is someone still working on this? if not, I'm a contributor at GSSOC24 and I would like to work on this issue. Please assign this to me.
