### ISSUE TITLE
BUG: No signin Form

### ISSUE THREAD

**Issue by AMISH-KHAN** [PatilHarshh/Kaam-Do#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current UI does not have a sign in form

https://github.com/PatilHarshh/Kaam-Do/assets/123164129/9588d584-10a3-4116-8fd6-538d19f9e873

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pulkit49** [comment]
I can help you with that. I have worked on a jobs website before. Please assign me under GSSOC 2024.
