### ISSUE TITLE
BUG: Cards overlapping (Not responsive)

### ISSUE THREAD

**Issue by sharmi4590** [PatilHarshh/Kaam-Do#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @PatilHarshh 
The cards are overlapping, I would like to solve this issue.

![Screenshot (500)](https://github.com/PatilHarshh/Kaam-Do/assets/102676949/68c417b1-ed60-4d17-8ca5-74bd4834d3e0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go Ahead !!
