### ISSUE TITLE
Feat: To add Contact form

### ISSUE THREAD

**Issue by ayush-848** [PatilHarshh/Kaam-Do#180]
### Describe the feature

The contact link is currently empty. I want to make it direct to a contact form

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/126975547/4804ac89-faa5-40ee-9725-6cd36016c4b6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@PatilHarshh Please assign this issue to me.

**Comment by PatilHarshh** [comment]
Go Ahead !!
