### ISSUE TITLE
BUG: Multiple UI changes required for responsiveness 

### ISSUE THREAD

**Issue by Mohitbagul** [PatilHarshh/Kaam-Do#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# What happened?

Hey @PatilHarshh,
  I have gone through the website and I have find multiple bugs that are making website unresponsive.
  
# Video describing the issue:
https://github.com/PatilHarshh/Kaam-Do/assets/126978039/53cb966d-59bc-4144-965b-85c8f7e0cf9b

Could you please assign me this issue and mark the issue label as **gssoc**. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
@Mohitbagul Exactly ! Where did you find the unresponsiveness? Mention

**Comment by Mohitbagul** [comment]
Yes @PatilHarshh,

I solve the following problems:

1) User is unable to click the button on navbar elements (he has to click the text rather which is annoying).
2) The pointer doesn't converts to a cursor when hovered over input boxes and some cards.
3) There should be less gap between elements in the footer sections company, policy, support.
4) The format of email should be verified in the section of subscribe.
5) In the find jobs page the job type and experience section can't be contract by clicking on the enlarge/contract button.
6) In the Companies page the divisions of listed companies are needed to be smaller in width.

Please assign me this issue with the **gssoc** tag.

**Comment by PatilHarshh** [comment]
Go Ahead @Mohitbagul
