### ISSUE TITLE
BUG: The typed text on the Country input is not visible accordingly.

### ISSUE THREAD

**Issue by Mohitbagul** [PatilHarshh/Kaam-Do#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On the Companies page the area where we can type country name for searching, the typed country name is not appearing at its place.

I would like to fix this issue.

# Video description for the bug

https://github.com/PatilHarshh/Kaam-Do/assets/126978039/523e7260-79f3-4c03-b280-187a5f2cbc76

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go Ahead @Mohitbagul
