### ISSUE TITLE
Feat: Feature for new job alerts.

### ISSUE THREAD

**Issue by Mohitbagul** [PatilHarshh/Kaam-Do#194]
### Describe the feature

This feature includes adding a new a sliding window or a section just below the navbar on the top which can mention new jobs alerts etc.

I will add this feature so that in the future the admin can add new updates for the candidates to apply by grabbing their attention.

### This is image from a e-commerce website but similarly we can add alerts for new jobs.

![Screenshot (388)](https://github.com/PatilHarshh/Kaam-Do/assets/126978039/df66ac34-7975-4698-ad6c-dd1b610f3949)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mohitbagul** [comment]
Hello @PatilHarshh can you assign me this issue please.

**Comment by PatilHarshh** [comment]
I think there is no need of such Crousel
