### ISSUE TITLE
BUG:enhance the footer

### ISSUE THREAD

**Issue by Varsani2520** [PatilHarshh/Kaam-Do#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in footer,
link is not working and as well as theme is not matched with our web

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,
assign this issue ,
i can do better , i know you will like it
i put my effort to design and enhance the footer ,because i know footer is important part of website

**Comment by PatilHarshh** [comment]
Go Ahead ! @Varsani2520

**Comment by Varsani2520** [comment]
Thank you @PatilHarshh
