### ISSUE TITLE
Feat:add search option for search the job

### ISSUE THREAD

**Issue by Varsani2520** [PatilHarshh/Kaam-Do#199]
### Describe the feature

we can add search functionality ,when user search then display that job .

steps:
add search ui
logic for search functionality
design search card

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/ebd77490-36f4-405e-be8a-f8cb87744af3)
here we can add search functionality for that display that job user search 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,
assign this issue,
i can do like a amazon and flipkart

**Comment by PatilHarshh** [comment]
Go Ahead @Varsani2520

**Comment by Varsani2520** [comment]
thank you for giving me this oppertunity @PatilHarshh
