### ISSUE TITLE
Feat: fixing css of  companies page

### ISSUE THREAD

**Issue by dhairyagothi** [PatilHarshh/Kaam-Do#200]
### Describe the feature

 i can make page look more good by editing css please assign this to me under gssoc @PatilHarshh 

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/142989448/92c49849-0c4b-4063-afeb-08460b7c562a)

i can make this look good

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go Ahead ! @dhairyagothi

**Comment by dhairyagothi** [comment]
> Go Ahead ! @dhairyagothi 

Thanku so much
