### ISSUE TITLE
Feat:Dark mode theme for website 

### ISSUE THREAD

**Issue by Prithwi32** [PatilHarshh/Kaam-Do#201]
### Describe the feature

In the current world people like to use dark mode theme more, so introducing dark theme for website increases User Experience and increases more usable of our website.

### Add ScreenShots

![Screenshot_2024-06-05-18-32-17-025_com android chrome-edit](https://github.com/PatilHarshh/Kaam-Do/assets/115262737/75a7e74c-2238-442e-ae5f-d17500c1c5f9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go Ahead @Prithwi32

**Comment by Prithwi32** [comment]
@PatilHarshh could you please add level to this issue and close as pr done
