### ISSUE TITLE
UI/UX

### ISSUE THREAD

**Issue by MehtabAsHellic** [PatilHarshh/Kaam-Do#202]
Hi Admin,

I'm interested in contributing to your project as part of GSSoC. I've been following your work and believe my skills align well. You can find my portfolio here: (https://sites.google.com/view/uibymehtab) and LinkedIn (https://www.linkedin.com/in/mehtabarkhan/)

Thanks,
Mehtab

**Comment by PatilHarshh** [comment]
What changes you want to make @MehtabAsHellic  ?
