### ISSUE TITLE
About us or Contact us Page

### ISSUE THREAD

**Issue by ananyabansal16** [PatilHarshh/Kaam-Do#203]
An About Us or Contact Us page is really necessary when it comes to a service-based website such as Kaam Do, and I am skilled at this task and will start working on this immediately. Kindly assign this task to me under GSSoC'24.

**Comment by PatilHarshh** [comment]
@ananyabansal16 Contactus Page is assigned to Someone ! Meanwhile you can Go Ahead with Aboutus Page !
Design good One
