### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by NalinDalal** [PatilHarshh/Kaam-Do#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Filters not working in the given website

say i only select intern option then the site must render the options only fitting the job description. Hence making it more responsive and user friendly

As u can see that even though I selected intern as option, it only shows full time offers
<img width="1440" alt="Screenshot 2024-06-06 at 15 08 40" src="https://github.com/PatilHarshh/Kaam-Do/assets/116961144/e9fa7e6c-a3ef-48da-b326-297a03ac87d2">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go Ahead @NalinDalal
