### ISSUE TITLE
FEATURE Add

### ISSUE THREAD

**Issue by SDprogramer** [PatilHarshh/Kaam-Do#208]
### Describe the feature

I want to make these buttons work.

Data scientist,  developer, full stack developer etc.

I am currently under gssoc. Please assign this issue to me and add the required labels.

### Add ScreenShots

![Screenshot 2024-06-06 154444](https://github.com/PatilHarshh/Kaam-Do/assets/155221332/339f2fce-87c3-4868-929c-2e1ee46ed854)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go Ahead

**Comment by SDprogramer** [comment]
![Screenshot 2024-06-07 155812](https://github.com/PatilHarshh/Kaam-Do/assets/155221332/470e61bc-7b31-4811-abe7-bbf009fb7716)

Under this heading of javascript file i have to write the backend program ??
And could you please tell me under which html file the popularSearch code is written ??

**Comment by SDprogramer** [comment]
ping @PatilHarshh

**Comment by SDprogramer** [comment]
![Screenshot 2024-06-08 165709](https://github.com/PatilHarshh/Kaam-Do/assets/155221332/23519f92-0824-4e10-8f5e-643d54c3b9e6)


Is it the correct way ?

**Comment by SDprogramer** [comment]
Ping @PatilHarshh
