### ISSUE TITLE
Feat: link to redirect officials careers portal

### ISSUE THREAD

**Issue by Mubashir2611** [PatilHarshh/Kaam-Do#212]
### Describe the feature

**Hey @PatilHarshh I want to redirect/link these cards to the official careers portal of that particular companies.so please assign me to this feature. ASAP :)**

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/108177382/b023ca32-db98-472d-b166-ef355bd47de0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
What's Your Thought ? means you want to add simply links to each image or Card ? or what @Mubashir2611

**Comment by Mubashir2611** [comment]
Actually I want to add links on these section that can redirect official career portal by help of the links. User can re directly reach the official career portal and they can searching for the jobs or applying the jobs.

**Comment by Mubashir2611** [comment]
@PatilHarshh Hey can you assign me or not?
