### ISSUE TITLE
Feat: Resume builder

### ISSUE THREAD

**Issue by mukilan2815** [PatilHarshh/Kaam-Do#215]
### Describe the feature

I can add resume builder option in this website so that user can easily build the resume with this website.

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/71129858/c82fabf2-1d19-4b60-b180-b8d564060580)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
This Need To Much Work @mukilan2815  !!

**Comment by PatilHarshh** [comment]
Go Ahead !! @mukilan2815
