### ISSUE TITLE
Feat: Style to Scrollbar

### ISSUE THREAD

**Issue by zalabhavy** [PatilHarshh/Kaam-Do#217]
### Describe the feature

There is default scrollbar in this website i will style it.

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/126322584/91c6b0e3-bdf8-48e8-83ee-c0132d69d54f)

This is default scrollbar i will style that.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@PatilHarshh Can you please assign me this!

**Comment by PatilHarshh** [comment]
go ahead @zalabhavy
