### ISSUE TITLE
BUG: Signing up issue

### ISSUE THREAD

**Issue by mohit-bhandari45** [PatilHarshh/Kaam-Do#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Description:-**
So after clicking the signin button, we are redirected to the same home page.
I dont't know if this is a bug or done appropriately. Please address this issue and update me.
If this is a bug, Assign this to me and 2-3 more people under gssoc24.
Label it level3.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by saurabhbakolia** [comment]
I would like to work on this issue.
