### ISSUE TITLE
Faq's section with accordian

### ISSUE THREAD

**Issue by Che140401** [PatilHarshh/Kaam-Do#220]
### Describe the feature

We can add Faq's section to understand more about projects

https://github.com/PatilHarshh/Kaam-Do/assets/109230049/136ed7bf-cb18-4481-893f-f13e22e6c23a

### Add ScreenShots

![Screenshot 2024-06-07 201728](https://github.com/PatilHarshh/Kaam-Do/assets/109230049/4210ce8f-d7e3-4b61-bd80-57af690352e2)
![Screenshot 2024-06-07 201744](https://github.com/PatilHarshh/Kaam-Do/assets/109230049/037589fb-4258-4246-a073-653083801793)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
@Che140401  go ahead
