### ISSUE TITLE
Feat: Swiper in the companies 

### ISSUE THREAD

**Issue by namandude** [PatilHarshh/Kaam-Do#233]
### Describe the feature

Hey i would  like to add the swiper functionality in the company  section so that it looks  more beutiful and engaging rather than all messed up in one places , by this we add any amount of cards which  add additonal info to user .

### Add ScreenShots

![Screenshot 2024-06-11 101530](https://github.com/PatilHarshh/Kaam-Do/assets/118013565/426e3e84-f446-45ab-90d7-d4569d531c18)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
what changes you want to do @namandude ?
