### ISSUE TITLE
Feat:Adding Feedback form and user ratings

### ISSUE THREAD

**Issue by Praveenkumar5048** [PatilHarshh/Kaam-Do#234]
### Describe the feature

I would like to add the feedback button in the frontend which collects users feedback and ratings. This feature is important to understand users views about our application. I would also implement the backend logic to store these feedbacks in the MongoDB database.
Please assign me this under Gssoc, I will finish this asap.

### Add ScreenShots

![Screenshot 2024-06-11 111015](https://github.com/PatilHarshh/Kaam-Do/assets/147526027/45beff09-ce53-4286-9767-7ff896845679)

This is the sample of the feedback form

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Praveenkumar5048** [comment]
@PatilHarshh sir can u assign this issue to me.

**Comment by PatilHarshh** [comment]
go ahead @Praveenkumar5048
