### ISSUE TITLE
Feat: Add UI sign in / sign up page 

### ISSUE THREAD

**Issue by DevGajjar28** [PatilHarshh/Kaam-Do#237]
### Describe the feature

current app does not contain sign in/ sign up. I would like to add sign in/ sign up page UI.

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/145287513/1f60f8ed-ec0e-4c9d-b62b-2c4d777f7eb1)
![image](https://github.com/PatilHarshh/Kaam-Do/assets/145287513/3ab2ac02-a04d-4104-9c5d-29650701f3b6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gokilp** [comment]
please assign to me

**Comment by DevGajjar28** [comment]
@PatilHarshh assign me
