### ISSUE TITLE
Feat: Add "Privacy Policy" and "Terms and Conditions" Pages to Kaam Do

### ISSUE THREAD

**Issue by MastanSayyad** [PatilHarshh/Kaam-Do#241]
### Describe the feature

@PatilHarshh 
To ensure legal compliance and build trust with users, it is essential to add Privacy Policy and Terms and Conditions pages to the "Kaam Do" platform. These pages will provide users with clear information about data usage, rights, and responsibilities.

### Add ScreenShots

These pages should be accessible via links in the website footer.

![image](https://github.com/PatilHarshh/Kaam-Do/assets/101971980/88220f85-ca61-47d0-9960-6dd489218e8b)

could you please assign this issue to me under gssoc?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
go ahead @MastanSayyad
