### ISSUE TITLE
Feat: footer is not appropriate 

### ISSUE THREAD

**Issue by siddhant-2002** [PatilHarshh/Kaam-Do#245]
### Describe the feature

i can give good css and enhance footer  and copyright is also not aligned good

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/112260375/2606992b-2b11-42b8-ba64-e66513ad925f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
what changes you want to make @siddhant-2002

**Comment by siddhant-2002** [comment]
1. first make copyright good align to center 
2. padding and margine to whole div 
3. align all divs to center increase some font 
4. there is too much space in between company and support links etc.

**Comment by PatilHarshh** [comment]
Go ahead @siddhant-2002  design good one !

**Comment by siddhant-2002** [comment]
![image](https://github.com/PatilHarshh/Kaam-Do/assets/112260375/e73f30ff-4703-4ff7-9a7f-7d852fac6f11)
