### ISSUE TITLE
Feat:Navbar is not appropriate

### ISSUE THREAD

**Issue by PAPIYA-DUTTA** [PatilHarshh/Kaam-Do#246]
### Describe the feature

I want add some good hover effect and enhance the navbar with sign up and login and also want add dark mode option

### Add ScreenShots

![img5](https://github.com/PatilHarshh/Kaam-Do/assets/118613949/738e5775-091c-48f8-9cad-23102eed437c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
what changes you want to make @PAPIYA-DUTTA ?
