### ISSUE TITLE
BUG:in dark mode text not display

### ISSUE THREAD

**Issue by Varsani2520** [PatilHarshh/Kaam-Do#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in dark mode theme search input text not display
![image](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/eb6b5af3-1b57-4a1e-a0d8-9e6be82f6012)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@PatilHarshh ,assign this issue

**Comment by Varsani2520** [comment]
@PatilHarshh ,assign me

**Comment by PatilHarshh** [comment]
Hello @Varsani2520  I saw your previous work related to frontend. I am developing a Project related to GATE aspirants . looking for teammates who are best in frontend. if you are interested or you  can suggest me such person. !! 

Benifits 👍  

1) This Project can be allowed to showcase in your Resume.
2) Collaboration with devs

**Comment by ranjaniav1** [comment]
Yes I am Intersted @PatilHarshh
