### ISSUE TITLE
Feat: Smooth Scroll effect

### ISSUE THREAD

**Issue by rahul-shrivastav** [PatilHarshh/Kaam-Do#251]
### Describe the feature

I will add smooth auto scroll to the website , please assign this task to me under GSSOC 24

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/114675655/60dfc53b-0401-4286-9ef3-3ce0b6d7b404)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
what changes you want to make ? @rahul-shrivastav

**Comment by rahul-shrivastav** [comment]
Add smooth scroll effect to page like when you are at bottom of home and click home button in navbar you auto scroll to top of the page
