### ISSUE TITLE
Feat:contact us section is not in website

### ISSUE THREAD

**Issue by siddhant-2002** [PatilHarshh/Kaam-Do#253]
### Describe the feature

contact us section is also not there in the website so I want to create it

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/112260375/14600bcf-4526-4572-a07d-fe21453c0a91)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by adityasingh-0803** [comment]
no contact us is there and when we try to click on email it expands chat support must be there too

**Comment by siddhant-2002** [comment]
hey @PatilHarshh any updates? about contact page

**Comment by siddhant-2002** [comment]
hey @PatilHarshh if you dont want to add further features its ok but atleast pages should be there i think backend part will do later
