### ISSUE TITLE
Feat: 404 page

### ISSUE THREAD

**Issue by Jagpreet153** [PatilHarshh/Kaam-Do#254]
### Describe the feature

I would like to add a responsive 404 error page with home button 

### Add ScreenShots

![Screenshot 2024-06-16 003919](https://github.com/PatilHarshh/Kaam-Do/assets/119691733/0661efe9-ec86-4834-b553-3fd9afd22b84)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by PatilHarshh** [comment]
go ahead @Jagpreet153
