### ISSUE TITLE
Feat: BLOGS page in dark mode 

### ISSUE THREAD

**Issue by siddhant-2002** [PatilHarshh/Kaam-Do#259]
### Describe the feature

1. blog page in dark mode is not up to date 
2. it has very low quality CSS also I want to add high quality stiling hover effect and zoom effect also
3. and images of that blog sections are also large small I will fix that also 

### Add ScreenShots

Uploading job do.mp4…

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go ahead !
