### ISSUE TITLE
ELABORATE AND IMPROVE README.MD

### ISSUE THREAD

**Issue by VShalini01** [PatilHarshh/Kaam-Do#26]
### What's wrong with the existing documentation

I am interested to add more information and make the Section of "Installation" and make it precise and understandable. As a part of GSSoC'24, I would like to make this contribution/enhancement.
I want to add more information about the application and elaborate the Installation section.
@PatilHarshh Please assign this issue to me sir.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
@VShalini01 Go Ahead !
