### ISSUE TITLE
Feat: Add a "Feedback Form/Page" to The Website

### ISSUE THREAD

**Issue by MastanSayyad** [PatilHarshh/Kaam-Do#261]
### Describe the feature

Hey @PatilHarshh 

I would like to add a feedback form/page

### Use Case
- User: Clicks on the "Feedback" Link (in Navbar and Footer)
- System: Displays the feedback form.
- User: Fills out the feedback form, providing optional name and email, selecting the type of feedback, and entering comments.
- User: Clicks the "Submit" button on the form.
- System: Displays a direct mail containing feedback

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/101971980/4d4141bb-1164-4bf0-9ddb-ea7bef81e4c0)

![image](https://github.com/PatilHarshh/Kaam-Do/assets/101971980/3a8a89ff-0b1a-4f25-bc62-17b9a948f197)

**Like this:**

![image](https://github.com/PatilHarshh/Kaam-Do/assets/101971980/f794f9c2-7f5f-41a4-9213-0309e1686c4e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sharmi4590** [comment]
@PatilHarshh Could you please assign me this task if it is still stale.
