### ISSUE TITLE
Add a Rate Us Option 

### ISSUE THREAD

**Issue by sailaja-adapa** [PatilHarshh/Kaam-Do#270]
### Describe the feature

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option on navbar it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24

### Add ScreenShots

![Screenshot_20240619_091731](https://github.com/PatilHarshh/Kaam-Do/assets/161804629/a350abcf-ab4e-4595-8f7f-0d7b8028b403)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go ahead !! are you able to work in backend too ?

**Comment by sailaja-adapa** [comment]
Can you assign me a level label

**Comment by PatilHarshh** [comment]
go ahead !!

**Comment by sailaja-adapa** [comment]
@PatilHarshh yeah thank you :)
