### ISSUE TITLE
BUG:Filter search not working

### ISSUE THREAD

**Issue by Varsani2520** [PatilHarshh/Kaam-Do#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/f6a060bc-97fe-48c4-89b0-8246a35a9c9e)
here issue is part time ,experiance level work not perfectly 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@PatilHarshh ,please assign this issue ,i can do like  amazon

**Comment by Varsani2520** [comment]
@PatilHarshh ,please assign this me

**Comment by PatilHarshh** [comment]
go Ahead

**Comment by Varsani2520** [comment]
@PatilHarshh ,please add the level
