### ISSUE TITLE
BUG:Effective Ui of Resume

### ISSUE THREAD

**Issue by Varsani2520** [PatilHarshh/Kaam-Do#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

here resume user Interface is not like a resume look :
![image](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/fa9f0d2a-466d-4e82-a5b3-9f06376dc2f5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@PatilHarshh ,please assign this issue

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,also add the level 1,2,or 3

**Comment by Varsani2520** [comment]
i make a resume like a proffessional

**Comment by PatilHarshh** [comment]
@Varsani2520

**Comment by PatilHarshh** [comment]
@Varsani2520  was too much busy. unable to maintain the repo ! or assign issue to the contributors ! will you interested to handle issue assign part to contributor?

**Comment by ranjaniav1** [comment]
close as a completed

**Comment by PatilHarshh** [comment]
are you interested in assigning issues to contributors in this repo?

**Comment by PatilHarshh** [comment]
@Varsani2520
