### ISSUE TITLE
BUG: Improve Newsletter

### ISSUE THREAD

**Issue by Khushi-Pushkar** [PatilHarshh/Kaam-Do#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/PatilHarshh/Kaam-Do/assets/142687709/049428e7-a76a-460f-8884-70cc486b379c)
We have noticed that the text in the newsletter becomes unreadable when viewed in dark mode. We need to adjust the color scheme to ensure readability .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
check once again!
