### ISSUE TITLE
BUG: Change Cursor style on hovering Scroll to top button and more UX improvements

### ISSUE THREAD

**Issue by vansh-codes** [PatilHarshh/Kaam-Do#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The cursor style of scroll to top button should be pointer instead of arrow to tell the user that it is a clickable button to improve the UX of the user. Also to remove the hover from the front page as it creates false impact on the user and disturbs the UX.

![image](https://github.com/PatilHarshh/Kaam-Do/assets/114163734/5302f7fb-1ecd-4d7e-b131-b61bf98ea4a7)

On hovering these three lines with a tick mark, the color changes to blue which makes user feel it as a button but actually it is not. This color change on hover need to be removed to improve the UX.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nikhilnishadoo7** [comment]
Hi there! I'd like to contribute to this project. Can you please assign this issue to me?

Thank you!

**Comment by vansh-codes** [comment]
> Hi there! I'd like to contribute to this project. Can you please assign this issue to me?
> 
> Thank you!

@nikhilnishadoo7 I am already assigned the task and I have completed the task as well. I have one PR pending already to be merged that's why I haven't created PR for this. So please close your PR as this issue is assigned to me and I have done it already. So please understand and close your PR.

@PatilHarshh Please don't assign this issue to him as I am active and I have completed the task as well. I already have a PR pending please merge that then I will be raising PR for this issue.
Thank you! I hope you understand.
