### ISSUE TITLE
BUG: Footer in Dark mode

### ISSUE THREAD

**Issue by dhruv8433** [PatilHarshh/Kaam-Do#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@PatilHarshh 

check this out,
footer background not changed in dark mode

![image](https://github.com/PatilHarshh/Kaam-Do/assets/114583978/67b842d2-e5d5-4e27-9d9d-abf7728c3438)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go Ahead !

**Comment by dhruv8433** [comment]
Thank you
