### ISSUE TITLE
Feat: Add Google Translate

### ISSUE THREAD

**Issue by MuraliDharan7** [PatilHarshh/Kaam-Do#287]
### Describe the feature

I want to add google translate feature in the website,

### Add ScreenShots

![GoogleTranslate](https://github.com/PatilHarshh/Kaam-Do/assets/130668745/a56b6104-e40b-49e4-8795-47ee82761939)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go ahead !!
