### ISSUE TITLE
Feat:CI and CD pipeline

### ISSUE THREAD

**Issue by iritikyadav123** [PatilHarshh/Kaam-Do#292]
### Describe the feature

Continuous Integration (CI) and Continuous Deployment (CD) pipelines are essential practices in modern software development, offering numerous advantages that enhance the efficiency, reliability, and quality of software projects. Here are some key benefits:

Improved Code Quality.
Faster Delivery and Deployment,
Increased Collaboration and Transparency,
Enhanced Customer Satisfaction.
Implementing CI/CD pipelines brings a wide range of advantages, from improving code quality and speeding up delivery cycles to reducing risks and enhancing team collaboration. These benefits collectively contribute to the development of high-quality software, quicker time-to-market, and higher customer satisfaction, making CI/CD pipelines a cornerstone of modern software development practices

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
how do you implement this ? what's your thought process !!

**Comment by iritikyadav123** [comment]
First, I create a Dockerfile, then create two YAML files in the GitHub folder for the CI pipeline. I'll write some commands:

First, I write all the jobs that the CI has to follow.
Then, name the jobs.
Name the job machines.
Clone the repo on the machine.
Install dependencies.
Then, run lint checks to verify the flow.
