### ISSUE TITLE
BUG: ABOUT page content is not at all correct

### ISSUE THREAD

**Issue by HarshitGupta1511** [PatilHarshh/Kaam-Do#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to edit about us page content as it is same which is given by default, that doesn't tell anything about the project. I want to edit and improve the ABOUT page.
please assign this task @PatilHarshh 
<img width="1440" alt="Screenshot 2024-06-23 at 10 41 40 PM" src="https://github.com/PatilHarshh/Kaam-Do/assets/120268295/ddc3a1b7-72e4-425d-8787-d4fa03fc7373">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
go ahead
