### ISSUE TITLE
BUG:Hamburger and cross icons are not properly visible in dark mode.

### ISSUE THREAD

**Issue by meetarora10** [PatilHarshh/Kaam-Do#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The hamburger and cross icons are not properly visible in the dark mode.
Assign this task to me under and I can make the required changes and fix this issue.
![Screenshot (517)](https://github.com/PatilHarshh/Kaam-Do/assets/143121854/56f1cc07-f7f4-4458-b87c-dc283eb28ef3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Bliss011** [comment]
Can u please assign me this task?

**Comment by meetarora10** [comment]
@Bliss011 this was completed 3 weeks ago.
