### ISSUE TITLE
BUG: The name of the website is 'Kaam Do' and in the upload job section the salary is required in USD, which I feel is contradicting.

### ISSUE THREAD

**Issue by InshiyaRavat** [PatilHarshh/Kaam-Do#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-12 074153](https://github.com/PatilHarshh/Kaam-Do/assets/96529913/d9d9ba06-4262-497e-aea0-5e0a56e52bbb)

I would like to change it to INR. Please assign me this issue under gssoc'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
@InshiyaRavat Go Ahead !
