### ISSUE TITLE
BUG: In Dark mode  text is not visible in the blog section

### ISSUE THREAD

**Issue by GAVINESHWAR** [PatilHarshh/Kaam-Do#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the blog section, the text is not visible in dark mode, as the cards become the white plain background.

![image](https://github.com/PatilHarshh/Kaam-Do/assets/124431955/7e5c456a-3b25-4d5a-aa54-e4c980b57fc4)

@PatilHarshh , please  assign me this issue to make contribution to the project

Thank you

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nikhilnishadoo7** [comment]
@PatilHarshh , please assign me this issue i want contribute to this project
