### ISSUE TITLE
Feat: Adding hovering and border effects to find job page

### ISSUE THREAD

**Issue by GAVINESHWAR** [PatilHarshh/Kaam-Do#302]
### Describe the feature

In the job find page there is poor hovering , I would like to add the nice hovering and border effects to the jobs cards to make attractive.

@PatilHarshh assign me this issue to make contribution to the project.

Thank you

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/124431955/d12d7474-4f1b-493c-9c42-a7aaa41ecfac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by adityasingh-0803** [comment]
i can contribute to it
