### ISSUE TITLE
Continue with google authentication using firebase

### ISSUE THREAD

**Issue by naisargi17** [PatilHarshh/Kaam-Do#313]
### Describe the feature

Using firebase we can create authentication through google.

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/111778403/ed37845c-08b0-4288-b410-7ab9a6f5944c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go ahead
