### ISSUE TITLE
BUG: navbar is not alligned properly

### ISSUE THREAD

**Issue by prachita0504** [PatilHarshh/Kaam-Do#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-07-02 224750](https://github.com/PatilHarshh/Kaam-Do/assets/139040702/23edf3d5-757d-43f1-a1af-3f30133409df)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
go ahead !

**Comment by prachita0504** [comment]
please review my pr
