### ISSUE TITLE
BUG: showing misspelled

### ISSUE THREAD

**Issue by InshiyaRavat** [PatilHarshh/Kaam-Do#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-12 075913](https://github.com/PatilHarshh/Kaam-Do/assets/96529913/8dd524fc-837f-4498-bf7d-85eb45c4d836)

assign me this issue under gssoc'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
@InshiyaRavat Go Ahead !
