### ISSUE TITLE
BUG: SPELLING ERROR

### ISSUE THREAD

**Issue by abhay-sen** [PatilHarshh/Kaam-Do#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

"Correct spelling error in the job posting description on LinkedIn from 'meia' to 'media'."
![Screenshot 2024-05-12 121336](https://github.com/PatilHarshh/Kaam-Do/assets/144714595/fad68de1-bc5c-46e7-aa58-5d4b6bf60b54)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SanaAzeem512** [comment]
please assign this issue to me

**Comment by ishita2704** [comment]
i 
can solve this issue .please assign this to me ,also mark it as gssoc .Thankyou

**Comment by ishita2704** [comment]
I'd be happy to submit a pull request with the correction. Please let me know if you'd like me to proceed.
Thank you

**Comment by Soumya6Tiwari** [comment]
@PatilHarshh  kindly assign me this issue under GSSOC'24.

**Comment by dikshagupta3094** [comment]
@PatilHarshh Please assign this issue to me under GSSOC'24
