### ISSUE TITLE
Feat: UI update in Blog Page

### ISSUE THREAD

**Issue by anshkie** [PatilHarshh/Kaam-Do#362]
### Describe the feature

I want to update the fonts and look of the blog page so that It will be more user friendly and appealing. Right Now the whole UI is upside down

 

### Add ScreenShots

![Ui_update](https://github.com/user-attachments/assets/d5701025-78c4-45ea-9310-091815530fe9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Blacksujit** [comment]
@PatilHarshh 

PR is raised for this Issue Please  review it #364
