### ISSUE TITLE
Feat: Better UI for Footer section

### ISSUE THREAD

**Issue by somilyadav7** [PatilHarshh/Kaam-Do#38]
### Describe the feature

Improving the footer section. Footer is taking too much space. When email is to be entered, it is not visible.

### Add ScreenShots

Email font color is white and footer section needs to be small to look better and better allignment.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by prachita0504** [comment]
hey, I can make a better, good looking and responsive footer. I'm a contributor (GSSOC'24).

**Comment by yuvikaKathaith** [comment]
Is someone still working on this? if not, I'm a contributor at GSSOC24 and I would like to work on this issue. Please assign this to me.
