### ISSUE TITLE
Adding login and Sign up functionality to the site and then i connect with database only authenticated user enter the main page using jwt

### ISSUE THREAD

**Issue by surendar-05** [PatilHarshh/Kaam-Do#4]
Assign this issue to me I want to work on this?under Gssoc'24

**Comment by shrutib11** [comment]
I have experience with jwt token authentication, please assign this issue to me.

**Comment by Ashutowsh** [comment]
I have experience and proficiency in JWT token authentication, so can you please assign the issue related to this matter to me?

**Comment by Mr-mahato** [comment]
I'm interested in working on the open issue regarding the implementation of user authentication within the URL Shortener project. I have experience with Node.js, Express, MongoDB, and JWT token handling, which aligns well with the project's requirements.

I've reviewed the issue's description and requirements and feel confident that I can deliver a robust and secure authentication solution. I understand the need for proper error handling and am ready to address those aspects.

Would you be open to assigning this issue to me? I'm eager to contribute to the project and believe I have the skills necessary to complete this task within the estimated timeframe.

**Comment by PatilHarshh** [comment]
@surendar-05  We want two different Authentication including user login (job Seeker) as well as admin (job poster). which one you want to proceed with ?

**Comment by surendar-05** [comment]
I go with a job seeker login and register page

**Comment by Mr-mahato** [comment]
@PatilHarshh  please allow me to work on job poster admin one.

**Comment by Ashutowsh** [comment]
For the Admin Poster page, we have to change the user Schema a little bit by adding an extra field denoting whether the user is an admin(job poster) or a job seeker.
So in such a way, we can manage role-based authentication for different users.

So **I can work on job posters login and register routes**. I have experience in such kind of role-based authentication systems. Also, I am eager to contribute to this project.
So can you assign this issue to me?

**Comment by surendar-05** [comment]
This type of function i  worked on

**Comment by surendar-05** [comment]
This type of features I worked on already can we integrate the functionality both job seeker and job adder(admin)?

**Comment by dhyaneshsiddhartha15** [comment]
@PatilHarshh  I would like to work on this issue. I can implement the login and sign up functionality, connect with the database for authentication using JWT, and add 'Login with Google' functionality  too so that by clicking on Sign with Google User can actually Login with their Google Account. Please assign this issue to me under GSSOC'24 . Looking forward to contributing

**Comment by PatilHarshh** [comment]
its Too Long Now !! @surendar-05
