### ISSUE TITLE
BUG: Add favicon

### ISSUE THREAD

**Issue by gyanendra-baghel** [PatilHarshh/Kaam-Do#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Add new favicon (search icon or other) instead of default vite icon. This will provide more better look.

----
![favicon-bug](https://github.com/PatilHarshh/Kaam-Do/assets/116253053/cc27f6e9-8ef1-4154-985f-354e4a721c48)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Soumya6Tiwari** [comment]
@PatilHarshh  kindly assign me this issue under GSSOC'24, I want to work on it.

**Comment by PatilHarshh** [comment]
@gyanendra-baghel ! Go Ahead !!

**Comment by gyanendra-baghel** [comment]
Sir, I am not clear, label should be `gssoc` or `gssoc24`

**Comment by jayanththalla** [comment]
please assign me

**Comment by jay270804** [comment]
@PatilHarshh Sir, please assign this issue to me
