### ISSUE TITLE
Feat: Add top Arrow Button

### ISSUE THREAD

**Issue by gyanendra-baghel** [PatilHarshh/Kaam-Do#42]
### Describe the feature

This feature is important because, If the user searched and go too much down and wanted to comeback on top.

- Add top arrow button to move to the top.

@PatilHarshh Can you assign this task to me.

### Add ScreenShots

![images](https://github.com/PatilHarshh/Kaam-Do/assets/116253053/ada8b479-b30d-4212-a74a-4df36f4ef4a0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ekkaaditya200** [comment]
Hello sir, I would like to work on this, can you assign it to me.

**Comment by ekkaaditya200** [comment]
Add GSSoC and level labels to it. I want to work on this. Can you assign it to me?

**Comment by Soumya6Tiwari** [comment]
@PatilHarshh  kindly assign me this issue under GSSOC'24 .

**Comment by PatilHarshh** [comment]
@gyanendra-baghel  Go Ahead !!

**Comment by Soumya6Tiwari** [comment]
@PatilHarshh  kindly assign me this issue

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24. @PatilHarshh

**Comment by PatilHarshh** [comment]
Any Updates @gyanendra-baghel

**Comment by Soumya6Tiwari** [comment]
@PatilHarshh  please assign it to me.

**Comment by gyanendra-baghel** [comment]
I am working on this.
