### ISSUE TITLE
Feat: Error Handler for Backend API'S

### ISSUE THREAD

**Issue by JainPriya1234** [PatilHarshh/Kaam-Do#44]
### Describe the feature

hey @PatilHarshh , I want to make a general error handler that can handle all types of exceptions and errors in the backend.
So, please assign this issue to me.

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/91417671/8226499f-52c3-4d32-91eb-8080bd8bbbd9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
@JainPriya1234  Go Ahead !!

**Comment by PatilHarshh** [comment]
any updates @JainPriya1234 ! or may close issue
