### ISSUE TITLE
Feat: login and signup page

### ISSUE THREAD

**Issue by Rimaru06** [PatilHarshh/Kaam-Do#46]
### Describe the feature

i would like to add login page and signup page for this website 

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/118299308/f632372a-6b6b-4ccf-ba79-bcf363c11236)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Rimaru06** [comment]
and will write  backend for the login page  and signup page

**Comment by Paarisha1** [comment]
Can I go for frontend part

**Comment by InshiyaRavat** [comment]
i can help in the backend. assign this issue to me under gssoc'24

**Comment by PatilHarshh** [comment]
@Rimaru06 , @Paarisha1 , @InshiyaRavat  .... Go Ahead !! Please complete it ASAP! because too much duplicate issues on this !

**Comment by Suyash878** [comment]
@PatilHarshh I would like to work on this issue as well. I can provide a fully functional: Signup page with authorisation using json web tokens(jwt).

**Comment by PatilHarshh** [comment]
> @Rimaru06 , @Paarisha1 , @InshiyaRavat .... Go Ahead !! Please complete it ASAP! because too much duplicate issues on this !

Please Update your Local repository!! As Ui has changed

**Comment by Rimaru06** [comment]
as me and  @InshiyaRavat    both working on the project how will you distribute the point @PatilHarshh

**Comment by InshiyaRavat** [comment]
we are working on the backend side

**Comment by PatilHarshh** [comment]
> we are working on the backend side

what changes from your side ?

**Comment by PatilHarshh** [comment]
> as me and @InshiyaRavat both working on the project how will you distribute the point @PatilHarshh

I will manage it ! According to your work ! Don't worry !

**Comment by InshiyaRavat** [comment]
i have created the signup api and added bcrypt

**Comment by Rimaru06** [comment]
> > we are working on the backend side
> 
> what changes from your side ?

login api , midlleware jwtverify , jwt authentication , zod validation , bcrypt

**Comment by Rimaru06** [comment]
@PatilHarshh  me and  @InshiyaRavat   ready to make a PR for backend  and  for frontend  i'll make another PR

**Comment by AnanyaJain25** [comment]
If the issue is still pending I would like to over this.

**Comment by Rimaru06** [comment]
Login and signup page is completed just left with the little bit of functionality ,I'll make PR by tomorrow @PatilHarshh

**Comment by PatilHarshh** [comment]
We need to proceed with another !! it is pending over month

**Comment by PatilHarshh** [comment]
@AnanyaJain25  Go ahead for this issue

**Comment by Madanraj0519** [comment]
Hey I am interested in this issue, And I can complete both the front-end and the backend part, I assure you I can complete this as soon as faster
