### ISSUE TITLE
BUG: spelling mistake

### ISSUE THREAD

**Issue by InshiyaRavat** [PatilHarshh/Kaam-Do#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-14 092722](https://github.com/PatilHarshh/Kaam-Do/assets/96529913/beb97151-4a2f-4d88-93ec-e5602534f195)

spelling mistake.
assign me this issue under gssoc'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Don't Raise Issue for Particular Words @InshiyaRavat  !! . 
Try to Raise the issue Which really make change !!
Let me know there major spelling change required !!
