### ISSUE TITLE
[ BUG ]: Fix Search Functionality

### ISSUE THREAD

**Issue by chaitanyarora** [PatilHarshh/Kaam-Do#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Proper search functionality NOT UI just UI update

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chaitanyarora** [comment]
@PatilHarshh Sir I'm willing to work around this, could you please assign me this issue?

**Comment by PatilHarshh** [comment]
What Changes You want to make ? it is little Unclear to me ! @chaitanyarora

**Comment by chaitanyarora** [comment]
@PatilHarshh on it sir!

**Comment by PatilHarshh** [comment]
Go Ahead !!
