### ISSUE TITLE
cv upload and profile sharing feature

### ISSUE THREAD

**Issue by omneaa** [PatilHarshh/Kaam-Do#53]
### Describe the feature

we can add new feature in the project which the user who apply to job upload his cv and send the cv and his profile to the client. 
i can make this feature in server side and i need one make the client side
plz assign to me this task I'am gssoc'24 contributor

### Add ScreenShots

" "

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Great !! @omneaa  Nice idea ! You need to Team up for this issue ?

**Comment by Maroooooh** [comment]
I can help you , I can make the front end for this task @PatilHarshh 

+ I agree to follow this project's Code of Conduct
+ I'm a GSSOC'24 contributor
+ I want to work on this issue

**Comment by omneaa** [comment]
@PatilHarshh can you plz assign the task to me to make the server side and assign the client side to @Maroooooh 😊

**Comment by Dhevamuthu** [comment]
Can u please assign this issue for me under GSSOC 2024

**Comment by RoshanAnsy** [comment]
can I join your team for solving this issue ?

**Comment by ShampaShaw** [comment]
assign me this issue under gssoc'24

**Comment by ananyabansal16** [comment]
If this issue is still pending, I can work on this under GSSoC'24. Lemme know :)

**Comment by PatilHarshh** [comment]
@omneaa
