### ISSUE TITLE
Improve Footer Section

### ISSUE THREAD

**Issue by somilyadav7** [PatilHarshh/Kaam-Do#54]
Footer section taking too much space so making it small and better like below
![Screenshot 2024-05-16 002136](https://github.com/PatilHarshh/Kaam-Do/assets/95069908/ce523506-6d85-4f39-9096-362400ff1409)

**Comment by tejjhode** [comment]
I will Fix this Please Assign me Under GSSOC'24

**Comment by AKB2102** [comment]
I will try to fix it , Assign me under GSSOC'24
