### ISSUE TITLE
Feat: Improvements to the search section could involve adding suggestions for both country/city and job titles

### ISSUE THREAD

**Issue by tejjhode** [PatilHarshh/Kaam-Do#56]
### Describe the feature

By incorporating these suggestions, users can benefit from a more streamlined and user-friendly search experience. This enhancement aims to facilitate quicker and more accurate searches, ultimately improving user satisfaction and engagement with the platform.

### Add ScreenShots

Now
<img width="1562" alt="Screenshot 2024-05-16 at 10 07 42 AM" src="https://github.com/PatilHarshh/Kaam-Do/assets/119703867/ad53b75c-4627-4403-94a4-604a412711e7">

su
<img width="1240" alt="Screenshot 2024-05-16 at 10 08 26 AM" src="https://github.com/PatilHarshh/Kaam-Do/assets/119703867/1b8dae73-0fc7-4663-90c7-93feae65a6f4">
ggestion

This Project is made by me

Please Assign me this issue to me Under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by tejjhode** [comment]
Please Assign me this issue to me Under GSSOC'24

**Comment by PatilHarshh** [comment]
Looks Good !! Go Ahead !! @tejjhode

**Comment by tejjhode** [comment]
@PatilHarshh  can look please look at the pull request
