### ISSUE TITLE
Adding the Jobs API 

### ISSUE THREAD

**Issue by neelamnagarajgithub** [PatilHarshh/Kaam-Do#6]
As of Know there is a static data of jobs So,we can create a new REST ful API which can be created using the Traditional MVC architecture . where we can create a model and controllers and connect it to frontend . 

Can you assign me this issue under GSSOC'24

**Comment by PatilHarshh** [comment]
Seems Good ! Go Ahead 🚀 @neelamnagarajgithub

**Comment by Ansh101112** [comment]
Hey, could you assign me this issue as I am familiar with this and make it a quick and fast optimized API service for the website available too @PatilHarshh .

**Comment by neelamnagarajgithub** [comment]
Solved this issue unde pr #10

Created a total Jobs RESTFUL API

CREATED

Jobs-Model✅
Jobs-Controller✅
Job Route✅
and using middleware connected to /api/v1/Jobs

we can
✅create a new Job by sending post request to /api/v1/Jobs
✅get all job details by sending get request to /api/v1/Jobs
✅we can update and delete the Jobs details by sending the patch and delete request to /api/v1/Jobs/id
✅ we can get a particular job details by sending get by id request to /api/v1/Jobs
