### ISSUE TITLE
UI enhancement  for company list under companies section

### ISSUE THREAD

**Issue by arjunatapadkar** [PatilHarshh/Kaam-Do#60]
### **Describe the feature**
By incorporating these suggestions, users can benefit from a more streamlined and user-friendly experience. This enhancement aims to facilitate quicker and more accurate searches, ultimately improving user satisfaction and engagement with the platform.

### **Add ScreenShots**

![Screenshot (170)](https://github.com/PatilHarshh/Kaam-Do/assets/99797400/e8203ca3-2640-4370-a33d-9a8fc64f8680)

Please Assign me this issue to me Under GSSOC'24

Record

- [x]  I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [x]  I want to work on this issue

**Comment by arjunatapadkar** [comment]
@PatilHarshh, Please Assign this issue to me Under GSSOC'24

**Comment by arjunatapadkar** [comment]
Hello @PatilHarshh  please assign the issue

**Comment by PatilHarshh** [comment]
what changes you want to make ? @arjunatapadkar
