### ISSUE TITLE
Improving the UI of nav bar

### ISSUE THREAD

**Issue by RohithgowdaM** [PatilHarshh/Kaam-Do#61]
### Describe the feature

The current nav bar background is not set and adding animations will help it to look better, I am willing to improve this nav bar, so i request you to assign me with this task.

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/105234575/887f706a-96dd-4438-8e83-9160903d6903)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
go Ahead !! @RohithgowdaM

**Comment by amanjaiswal7236** [comment]
Hey @PatilHarshh , I also love to contribute to this, can you also assign me to this please.
