### ISSUE TITLE
Feat: job search bar

### ISSUE THREAD

**Issue by AKB2102** [PatilHarshh/Kaam-Do#63]
### Describe the feature

the job search bar is located right above the image which is not looking very presentable it can be moved down a bit 
I hope you can assign me ...

### Add ScreenShots

it can rather look like this....
![Screenshot 2024-05-16 225158](https://github.com/PatilHarshh/Kaam-Do/assets/129149776/8d5194d5-3e0d-4888-b8ee-00c82a2e85ff)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
@AKB2102  Its Ok there !!
