### ISSUE TITLE
BUG:On  upload job section the details are not Submitting

### ISSUE THREAD

**Issue by tejjhode** [PatilHarshh/Kaam-Do#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The details on the upload job section fail to submit and require correction and enhancement to be more appealing.
<img width="1680" alt="Screenshot 2024-05-16 at 11 12 46 PM" src="https://github.com/PatilHarshh/Kaam-Do/assets/119703867/713791c8-42e0-43de-84e8-6bd00c5e118f">

I can both rectify the submission issue and develop the backend for it.

Please Assign me this under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ekansh0801** [comment]
I Have understood the error and i am ready for contributing on the error
please assign task to me 

## Record
 [ ] I agree to follow this project's Code of Conduct
 [ ] I'm a GSSOC'24 contributor
 [ ] I want to work on this issue
