### ISSUE TITLE
[FEATURE] Implement Page Loader Transition for Improved User Experience

### ISSUE THREAD

**Issue by yashmandi** [PatilHarshh/Kaam-Do#65]
### Describe the feature

Implementing a page loader transition on each page, when user goes from one page to another, theere should be a animated effect transition which enhances user experience.
Would like to work on this issue under GSSoC '24, request you to assign this issue to me :)

### Add ScreenShots

Would like to add loader similar to this on every page:

![loading](https://github.com/PatilHarshh/Kaam-Do/assets/132436131/7581c8a8-1043-4089-8770-88c480257bc1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go Ahead !! @yashmandi
