### ISSUE TITLE
BUG: Search not working

### ISSUE THREAD

**Issue by dhruv8433** [PatilHarshh/Kaam-Do#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@PatilHarshh 
Search function not working 

![image](https://github.com/PatilHarshh/Kaam-Do/assets/114583978/3d1602f7-edc8-49dd-907c-5554e1d44c1f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
check once again !!
