### ISSUE TITLE
BUG: Dummy Suggestions

### ISSUE THREAD

**Issue by dhruv8433** [PatilHarshh/Kaam-Do#70]
@PatilHarshh 
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This suggestion is not working
![image](https://github.com/PatilHarshh/Kaam-Do/assets/114583978/4e319d0e-ebcb-45a9-be35-870231a36938)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dhevamuthu** [comment]
please assign me this issue under GSSOC 2024
