### ISSUE TITLE
BUG:reDesign the about page UI

### ISSUE THREAD

**Issue by Varsani2520** [PatilHarshh/Kaam-Do#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@PatilHarshh ,
redesign the about page UI like this :
![About us page wireframe - Landing page](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/ac0d23ff-fbf2-41a5-a445-84408f94c056)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Much need !! @Varsani2520 !! can you redesign home page too ?

**Comment by Varsani2520** [comment]
@PatilHarshh ,
Sure i reDesign the home page as well as about page

**Comment by Varsani2520** [comment]
@PatilHarshh ,can you assign me

**Comment by Varsani2520** [comment]
@PatilHarshh ,
thank you

**Comment by Varsani2520** [comment]
@PatilHarshh ,
is this ok for home Ui?
![image](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/572dffd9-fb01-4080-bb70-0978995b535c)
![image](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/9733d51a-a247-4f5f-86cf-8d66a1669b20)
![image](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/22ab84a6-32a7-466c-b3e6-a0e887652ec5)
![image](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/43d98ef9-1c3b-40e2-a4d9-703697d9e8a1)
![image](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/ce720e10-10f5-4b37-98b9-800c03223a9e)

**Comment by PatilHarshh** [comment]
Nice ! @Varsani2520

**Comment by Varsani2520** [comment]
ok , @PatilHarshh

**Comment by Varsani2520** [comment]
@PatilHarshh 

can you tell me why you don't add level lable in this pr...!!
i recreated your home as well as about with nice and attractive look

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,assign label level
