### ISSUE TITLE
BUG: Filter Not Working

### ISSUE THREAD

**Issue by dhruv8433** [PatilHarshh/Kaam-Do#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Filter jobs not working
![image](https://github.com/PatilHarshh/Kaam-Do/assets/114583978/582383f1-a09a-4e5e-a2fc-eb9f3a89cd08)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go Ahead @dhruv8433

**Comment by dhruv8433** [comment]
Thank you @PatilHarshh
