### ISSUE TITLE
BUG:contact us missing

### ISSUE THREAD

**Issue by Varsani2520** [PatilHarshh/Kaam-Do#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@PatilHarshh ,
i think you forgot the contact page ,its a important part of e-commerce website
![image](https://github.com/PatilHarshh/Kaam-Do/assets/137641079/932b8ff2-54e5-4844-9eb9-70a7edfeb6b8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go Ahead !!

**Comment by Varsani2520** [comment]
thank you @PatilHarshh
