### ISSUE TITLE
BUG:Footer link are dummy

### ISSUE THREAD

**Issue by Varsani2520** [PatilHarshh/Kaam-Do#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@PatilHarshh ,
footer link is not work as a link ,add link for go to perticular page 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Right now we don't have links. Let you Know until we form our socials
