### ISSUE TITLE
Feat: Apply now Form 

### ISSUE THREAD

**Issue by dhruv8433** [PatilHarshh/Kaam-Do#75]
### Describe the feature

@PatilHarshh  
- When user click on apply now button we can open new form that take user information like phone, email, name, address and take resume for furture processing.
-  also user can add their exprience with particualr company

### Add ScreenShots

![image](https://github.com/PatilHarshh/Kaam-Do/assets/114583978/f1c7e2c6-172e-4be3-931c-22625f0a8e00)

we can build something like linked

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
@dhruv8433 Go Ahead !!

**Comment by dhruv8433** [comment]
@PatilHarshh  Thank you for providing me oppurnity

**Comment by mtg718** [comment]
@PatilHarshh  , please assign this task to me under gSSoC'24
