### ISSUE TITLE
BUG: There is no gap between banner and suggestion

### ISSUE THREAD

**Issue by dhruv8433** [PatilHarshh/Kaam-Do#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@PatilHarshh 

check out this there is not margin top between banner and suggestion box 
![image](https://github.com/PatilHarshh/Kaam-Do/assets/114583978/d5061ed6-3394-431f-b607-b7709810b70d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
No need of this ! we are changing our UI completely !!
