### ISSUE TITLE
BUG: FAQ page is missing

### ISSUE THREAD

**Issue by dhruv8433** [PatilHarshh/Kaam-Do#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@PatilHarshh 

There is no FAQ page 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go Ahead !! @dhruv8433  Add FAQ to the topic !! if i feel particular faq is not to the topic i will remove it !

**Comment by dhruv8433** [comment]
@PatilHarshh Thank you

**Comment by naisargi17** [comment]
can you please assign me under GSSOC.'24 .
