### ISSUE TITLE
BUG:add pagination

### ISSUE THREAD

**Issue by Varsani2520** [PatilHarshh/Kaam-Do#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@PatilHarshh ,
add pagination for showing per page 10 items

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dhevamuthu** [comment]
Please assign me this issue under GSSOC 2024 as I am currently doing few number of projects in mern currently.
