### ISSUE TITLE
Feat: Hovering effect for Job cards

### ISSUE THREAD

**Issue by Shelbybosss** [PatilHarshh/Kaam-Do#80]
### Describe the feature

I will add a smooth hovering effect for the cards which will improve the UI and be more interactive.

### Add ScreenShots

yes

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by PatilHarshh** [comment]
Go Ahead !!! @Shelbybosss

**Comment by Shelbybosss** [comment]
pull request created

**Comment by naisargi17** [comment]
can you please assign me under GSSOC.'24 .

**Comment by Shelbybosss** [comment]
@naisargi17 I have already done it, look for any other issue.

**Comment by Shelbybosss** [comment]
@PatilHarshh I just checked the live website, what have u merged, before the website was much more better now its looking as if some garbage. I'll advice u to revert the changed. and yeah for this issue i have already created a pull req do merge it
