### ISSUE TITLE
Feat: Adding a search functionality 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [PatilHarshh/Kaam-Do#85]
### Describe the feature

In the search box we can write any job title so that we can find best suited job .

### Add ScreenShots

![Screenshot 2024-05-18 092330](https://github.com/PatilHarshh/Kaam-Do/assets/118350936/9393e801-0806-4690-a272-42275edec1e6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dhevamuthu** [comment]
Please assign me this issue under GSSPC 2024

**Comment by Unnati101** [comment]
please assign this issue to me
