### ISSUE TITLE
Feat:Adding list of contributors image under readme

### ISSUE THREAD

**Issue by Arpcoder** [PatilHarshh/Kaam-Do#88]
### Describe the feature

List of contributors image under readme

### Add ScreenShots

![Screenshot 2024-05-18 121157](https://github.com/PatilHarshh/Kaam-Do/assets/100352419/514a8d00-c78c-4c92-81d5-bb14893a58f2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
go Ahead !
