### ISSUE TITLE
[FEAT] Implement the 'Salary Slider' in Filter Section

### ISSUE THREAD

**Issue by yashmandi** [PatilHarshh/Kaam-Do#90]
### Describe the feature

In the left side, the 'Filter Search' Section, we can add a range slider for user's preferred salary range he's looking for, according to the salary range we can sort the jobs. User can easily slide from start to end according to his required salary jobs.
 
Would like to work on this feature under GSSoC '24. Request you to assign this task to me :)

### Add ScreenShots

We can add this feature below 'Experience' Section:

![adsasdasd](https://github.com/PatilHarshh/Kaam-Do/assets/132436131/216a3c00-9a91-45b4-88ad-809c96ae8443)

I'm thinking of adding similar to this:

![salary-bar](https://github.com/PatilHarshh/Kaam-Do/assets/132436131/8312fa66-82f7-4606-9ede-a23e8f759dbe)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
There is no Use of this i think @yashmandi
