### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by aditi9402** [PatilHarshh/Kaam-Do#95]
### What's wrong with the existing documentation

The code of conduct file is missing. 
Please assign me this under gssoc 24

### Add ScreenShots

![Screenshot (719)](https://github.com/PatilHarshh/Kaam-Do/assets/114405540/ef4a4cce-b524-4980-b5da-2b89081d38fb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by suhanipaliwal** [comment]
Duplicate issue. Already raised #11
