### ISSUE TITLE
Feat: Workflow for auto commenting an issue creation

### ISSUE THREAD

**Issue by Asymtode712** [PatilHarshh/Kaam-Do#98]
### Describe the feature

This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

### Add ScreenShots

![issue creation](https://github.com/PatilHarshh/Kaam-Do/assets/115717746/2bc442e2-867d-46cd-a327-8e0016d123d6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@PatilHarshh please assign me this issue under gssoc'24

**Comment by PatilHarshh** [comment]
Go Ahead !! @Asymtode712
